branch-defaults:
  dev:
    environment: Capacity-env
environment-defaults:
  Capacity-env:
    branch: null
    repository: null
global:
  application_name: capacity
  default_ec2_keyname: capacity-prod
  default_platform: PHP 8.0 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
